trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .
    exclude:
      - .vscode
      - .gitignore
      - README.md

pr:
  branches:
    include:
      - main
  paths:
    include:
      - .
    exclude:
      - .vscode
      - .gitignore
      - README.md

pool:
  vmImage: ubuntu-latest

stages:
  - ${{ if or(ne(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')) }}:
      - template: .azure-pipelines/stages/deploy-preview-stage.yaml
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)
  - ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest')) }}:
      - template: .azure-pipelines/stages/deploy-prod-stage.yaml
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)
